#pragma once

#include "driver/gpio.h"

#define PRINT_DEBUG 1

#define LOW 0
#define HIGH 1
#define MATRIX_INPUT_PRESSED_STATE 0

#define MATRIX_ROWS 3
#define MATRIX_COLS 11
#define DEBOUNCE 10

#define TIMEOUT_TICKS 0
#define TIMER_RESOLUTION 1000000
#define TIMER_SCAN_DELAY 3000
#define TIMER_COUNT_START 0

#define MATRIX_COL_PINS { GPIO_NUM_0, GPIO_NUM_35, GPIO_NUM_4, GPIO_NUM_5, GPIO_NUM_6, GPIO_NUM_16, GPIO_NUM_15, GPIO_NUM_7, GPIO_NUM_17, GPIO_NUM_18, GPIO_NUM_8 }
#define MATRIX_ROW_PINS { GPIO_NUM_36, GPIO_NUM_37, GPIO_NUM_38 }

/* COL2ROW, ROW2COL*/
#define DIODE_DIRECTION COL2ROW
